// Code generated by MockGen. DO NOT EDIT.
// Source: manager.go

// Package actkn is a generated GoMock package.
package actkn

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockManager is a mock of Manager interface.
type MockManager struct {
	ctrl     *gomock.Controller
	recorder *MockManagerMockRecorder
}

// MockManagerMockRecorder is the mock recorder for MockManager.
type MockManagerMockRecorder struct {
	mock *MockManager
}

// NewMockManager creates a new mock instance.
func NewMockManager(ctrl *gomock.Controller) *MockManager {
	mock := &MockManager{ctrl: ctrl}
	mock.recorder = &MockManagerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockManager) EXPECT() *MockManagerMockRecorder {
	return m.recorder
}

// Decode mocks base method.
func (m *MockManager) Decode(src []byte, c *Ctx) []byte {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Decode", src, c)
	ret0, _ := ret[0].([]byte)
	return ret0
}

// Decode indicates an expected call of Decode.
func (mr *MockManagerMockRecorder) Decode(src, c interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Decode", reflect.TypeOf((*MockManager)(nil).Decode), src, c)
}

// Encode mocks base method.
func (m *MockManager) Encode(dst, src []byte, c *Ctx) []byte {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Encode", dst, src, c)
	ret0, _ := ret[0].([]byte)
	return ret0
}

// Encode indicates an expected call of Encode.
func (mr *MockManagerMockRecorder) Encode(dst, src, c interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Encode", reflect.TypeOf((*MockManager)(nil).Encode), dst, src, c)
}
